[package]
name = "loadymcloadface"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "loady"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
# hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.24", features = ["blocking", "rustls-tls"] }
futures = "0.3.31"
# http-body-util = "0.1"
# hyper-util = { version = "0.1", features = ["full"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
bytes = "1.10.1"
rand = "0.9.2"
async-channel = "2.5.0"
crossbeam = "0.8.4"
chrono = "0.4.42"
config = { version = "0.15.18", features = ["toml"] }
ctrlc = "3.5.0"
dotenv = "0.15.0"
libc = "0.2.177"
log = "0.4.28"
env_logger = "0.11.8"
csv = "1.4.0"
